# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
    - generators
    - linters
    - unit-tests

protos:
    stage: generators
    image: python:3.6
    only:
        - dev
        - web
    before_script:
        - pip install grpcio-tools
    script:
        - make protos

pep8:
    stage: linters
    image: python:3.6
    allow_failure: yes
    only:
        - dev
        - web
    before_script:
        - pip install flake8
    script:
        - flake8 hathor/ tests/ *.py

unit-tests:
    stage: unit-tests
    image: python:3.6
    only:
        - dev
        - web
    before_script:
        - apt update
        - apt install -y graphviz
        - pip install -r requirements.txt
    script:
        - pytest --cov=hathor --cov-fail-under=75 -p no:warnings ./tests
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
